fix: 使用canvas旋转图片，修复图片旋转排版问题，旋转按钮tip错误；feat: 添加图片向右旋转 #49
editablejs/editable pull request #50
Opened 2023-01-18 04:45 UTC by claviering

2023-01-18 05:21 UTC, big-camel requested changes

2023-01-18 05:21 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
在开启协作的情况下，url 被修改后会导致其它协作者客户端无法访问到图片。

2023-01-18 06:49 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
using canvas toDataURL API to get Base64 data rather then blob

2023-01-18 07:04 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
`base64` 也不是一个好办法

- url 会变得太长，传输或者做持久化存储不友好。

我有个建议

`rotate` 和 `url` 保持不变，变换的时候还是修改 `rotate` 属性，不修改 `url`

在图片显示的时候获取到 `rotate` 和 `url` ，然后使用 canvas 变换 toDataURL，最后赋值给 img 节点和 preview 节点

2023-01-18 07:51 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
当前上传图片的显示也是用 `base64`，`url`太长的话只能用网络地址。修改 `rotate ` 属性不能解决元素的占位，就出出现issues我截图那样子，图片错位

2023-01-18 07:55 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
使用`rotate `，点击查看大图，旋转的效果没有体现

2023-01-18 08:00 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
因为默认上传逻辑就是转的 `base64` ，实际使用的时候传入 `Upload` 自行返回图片服务器地址就可以了。

可以在图片渲染组件中生成，类似下面的逻辑：

```js
const [objectURL, setObjectURL] = useState('')

useLayoutEffect(() => {
 drawRotated(element.url, element.rotate).then(blob => {
     setObjectURL(URL.createObjectURL(blob))
})
}, [element.url, element.rotate])

...


return <img src={objectURL || url}/>
```

2023-01-18 08:11 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
用 `createObjectURL` 图片的 `URL` 还是blob 类型，开启协作，其它协作者客户端也一样无法访问到图片。

[Example: Using object URLs to display images](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_using_object_urls_to_display_images)

2023-01-18 08:14 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
> 实际使用的时候传入 `Upload` 自行返回图片服务器地址就可以了。

旋转之后也要重新上传服务器拿到返回的地址

2023-01-18 08:28 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
> 用 `createObjectURL` 图片的 `URL` 还是blob 类型，开启协作，其它协作者客户端也一样无法访问到图片。
> 
> [Example: Using object URLs to display images](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_using_object_urls_to_display_images)

我的意思是 `url` 不变，我们每次修改 `rotate` 值作为改变后的标志，例如它是 90、180 这类

当 `rotate` 值改变后，当前用户和协作者都会收到这个值的变化 

只需要在 `rotate` 变化后，重新生成一个旋转后的 `url` 给**当前图片**显示（仅仅用于显示，每次加载也需要重复这个过程），并不需要把这个新的 `url` 修改到文档结构上，在文档结构上还是之前的 `url` 地址。

其它协作者接收到 `rotate` 变化后，同样的也是按照上面的逻辑重新生成一个旋转后的 `url` 在协作者本地显示。

2023-01-18 08:30 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
> > 实际使用的时候传入 `Upload` 自行返回图片服务器地址就可以了。
> 
> 旋转之后也要重新上传服务器拿到返回的地址

旋转之后只是 `rotate` 值修改了，原图的 `url` 不修改，直接访问原图 `url` 还是未旋转之前的正常图片。只有在编辑器内加载的时候根据 `rotate` 值重新生成一个 objectURL 显示出来。

2023-01-19 02:30 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
我看了一下网络请求，虽然图片旋转之后 `url` 变化了，但是资源还是从 `memory cache` 中获取

2023-01-19 02:37 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
createObjectURL 不就是加载到内存中的吗

2023-01-19 02:59 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
现在旋转之后 再用 `canvas.toDataURL("image/png")` 修改原图的 `url` 是会有什么问题？

2023-01-19 03:17 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
主要还是 base64 太长了，持久化保存一个 base64 太占资源了。第二个通过协作传输也是一样的道理。

我更倾向于 base64 仅仅在用户本地显示，持久化保存还是原图 url 和 rotate ，当重新加载的时候再重新用 canvas 根据 url 和 rotate 重新创建旋转后的 base64 在用户本地呈现。

2023-01-19 03:23 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
持久化保存功能的代码在什么位置，我先看看

2023-01-19 03:29 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
协作写作的时候，为什么我看不到 `WebSockets` 的网络请求？

2023-01-19 03:34 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
这是开源库，当前demo没有持久化保存。但是得考虑到这个需求，有人使用可能会做持久化保存。另外通过ws传输base64也会需要大量网络资源，yjs也可以做持久化。

另外在我之前的想法上再加一个可选项，例如 RotateUpload 如果有配置就调用他上传，不修改 rotate，如果没有配置那就修改rotate，按之前的想法执行。

作为开源库我必须得考虑更多灵活的可能性来满足不同人的需求。

2023-01-19 03:35 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
> 协作写作的时候，为什么我看不到 `WebSockets` 的网络请求？

有一个端口为1234的/editable 的ws请求，数据传输的是压缩的二进制

2023-01-19 09:55 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
<img width="629" alt="image" src="https://user-images.githubusercontent.com/16227832/213411469-42a82378-2e24-4181-b897-c9b99047cc0b.png">

`packages/plugins/image/src/interfaces/image.ts` 你保存的这个Image url 不也是base64 ？

2023-01-19 09:59 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
说过了，这只是个demo，没写上传接口，默认用base64做上传演示。

2023-01-19 09:59 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
Blob URLs can only be generated internally by the browser. [URL.createObjectURL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) will create a special reference to the Blob or File object which later can be released using [URL.revokeObjectURL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL). These URLs can only be used locally in the single instance of the browser and in the same session (ie. the life of the page/document).

createObjectURL 生成的url也只是临时地址，所以一开始才导致协作的情况下其他人访问不了图片

2023-01-19 10:14 UTC, big-camel commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
> 说过了，这只是个demo，没写上传接口，默认用base64做上传演示。

withImage(editor, { onUpload: ...}) 在使用的时候，如果处理了上传逻辑，你可以自由的显示你定义的url或者资源

2023-01-20 03:05 UTC, claviering commented on packages/plugins/image/src/index.tsx
> +        url: URL.createObjectURL(blob),
我又改了，旋转之后调用 `uploadImage`, base64 做为上传的演示。 `onUpload ` 有处理上传逻辑还是走 `onUpload `

2023-01-20 12:11 UTC, big-camel commented
修改了一些逻辑，你帮忙看看。

2023-01-28 05:17 UTC, big-camel submitted a review, later dismissed

2023-01-28 10:47 UTC, claviering commented
可以合并了？

2023-01-28 11:36 UTC, big-camel commented
> 可以合并了？

还有点问题，得再调一下

2023-01-28 12:00 UTC, big-camel approved these changes

2023-01-28 12:00 UTC, merged