fix: #72
editablejs/editable pull request #73
Opened 2023-02-05 03:42 UTC by claviering

**Description**

A clear and concise description of what this pull request solves. (Please do not just link to a long issue thread. Instead include a clear description here or your pull request will likely not be reviewed as quickly.)

**Issue**

Fixes: (link to issue)

**Example**

A GIF or video showing the old and new behaviors after this pull request is merged. Or a code sample showing the usage of a new API. (If you don't include this, your pull request will not be reviewed as quickly, because it's much too hard to figure out exactly what is going wrong, and it makes maintenance much harder.)

**Context**

If your change is non-trivial, please include a description of how the new logic works, and why you decided to solve it the way you did. (This is incredibly helpful so that reviewers don't have to guess your intentions based on the code, and without it your pull request will likely not be reviewed as quickly.)

**Checks**

- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `pnpm test`.
- [ ] The linter passes with `pnpm lint`. (Fix errors with `pnpm fix`.)
- [ ] The relevant examples still work. (Run examples with `pnpm start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

2023-02-05 04:10 UTC, big-camel requested changes

2023-02-05 04:10 UTC, big-camel commented on packages/plugins/history/src/with-history.ts
> -        ) {
mege 这段代码不能删掉，否则不同位置输入中文都会合并到一起，撤销的时候多个地方的中文都会同时撤销掉。

2023-02-05 04:13 UTC, big-camel commented
另外加一下 changeset `pnpm changeset`

2023-02-05 08:03 UTC, claviering commented on packages/plugins/history/src/with-history.ts
> -        ) {
这里我换了另一种判断，你再看看，ts的类型判断有问题，我加不上

2023-02-05 08:05 UTC, claviering commented
> 另外加一下 changeset `pnpm changeset`

选择不了，不会用，按了回车键没有反应

<img width="553" alt="image" src="https://user-images.githubusercontent.com/16227832/216808257-a7efb450-96c4-48b9-bb7a-a53978b76128.png">

2023-02-05 08:06 UTC, big-camel commented
> > 另外加一下 changeset `pnpm changeset`
> 
> 选择不了，不会用，按了回车键没有反应
> 
> <img alt="image" width="553" src="https://user-images.githubusercontent.com/16227832/216808257-a7efb450-96c4-48b9-bb7a-a53978b76128.png">

按空格选中~

2023-02-05 08:23 UTC, claviering commented
好像要commit 之后才能选中

2023-02-05 08:30 UTC, big-camel commented
> 好像要commit 之后才能选中

在确定你需要发布一个新的版本情况下，在 `commit` 前，需要执行 `pnpm changeset` 生成`变更集`
   - 会列出 `changed packages`(所有有变动的包) 按下空格可以选中这些包，然后回车
   - 接着会询问 Which packages should have a **major** bump ? 
       - `major` 表示大版本变更，1.0.0 -> 2.0.0。
       - 此时按下回车会出现 Which packages should have a **minor** bump? `minor` 表示中等版本变更 1.1.0 -> 1.2.0，
       - 最后再一次回车会直接生成 `patch` 级别的变更，1.0.0 -> 1.0.1 。
       - 按需要选择你的变更版本级别。
    - 在确定你所需要的变更级别后，按下空格选中需要更新的包，然后回车，变更集就生成好了。
  
最后把生成的变更集和改动一起 `commit` 分支

2023-02-05 08:34 UTC, big-camel commented
为啥你的变更级还有个 @editablejs/docs ，这不是一个包来着~。

我修复了那个类型问题，而且还加上了 every ，整个 operations(它是一个所有变动的集合) 都在相同位置才会去合并。你看合理不？

2023-02-05 08:39 UTC, claviering commented
`pnpm changeset` 之后可能没选对，不会用
加上了 every，选择内容之后再输入中文，就 undo 不了了

2023-02-05 08:41 UTC, claviering commented
> `pnpm changeset` 之后可能没选对，不会用 加上了 every，选择内容之后再输入中文，就 undo 不了了

<img width="475" alt="image" src="https://user-images.githubusercontent.com/16227832/216809605-8ff90dd1-d49b-436e-b8c7-f9aa6f25a0f1.png">

同时选择不同格式

2023-02-05 11:31 UTC, big-camel commented
又改了下，我这测试没问题，你看看 @claviering 

另外我又加了一个 delay 模式，如果设置的话，会按未活动的时间间隔去选择 merge 或者 push，这是一般通用做法。

2023-02-05 15:43 UTC, merged

2023-02-06 02:19 UTC, claviering commented
OK